db_host: "localhost"
db_port: "5432"
db_user: "postgres"
db_password: "postgres"
db_name: "system_infodb"
db_sslmode: "disable"
db_url: "postgres://postgres:postgres@localhost:5432/system_infodb"
grpc_port: "11011"
http_port: "8080"
